image: gcc

ai-build:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf catch
  script:
    - cd ai && make release
  artifacts:
    paths:
      - ai/test

ai-test:
  stage: test
  script:
    - ai/test
